### ISSUE TITLE
Nice work, thanks for sharing

### ISSUE THREAD

**Issue by neilyoung** [gurhub/ScrollableStackView#4]
Was trying to add subviews loaded from XIB to no avail. Would that be possible at all?

**Comment by gurhub** [comment]
Hi and thank you :) Actually never tried before :) Contributions are always welcome, please feel free to send a pull request for this. You can add in the example project for example. ;)

Also, I don't have any free time to maintain this project anymore. But, I can review and send commits if needed any time.

Best
