### ISSUE TITLE
Support horizontal scrolling, axis switching

### ISSUE THREAD

**Issue by minorbug** [gurhub/ScrollableStackView#5]
Great work.

I’d like to see an option to switch axes, so we can scroll horizontally when rotating the iOS device.

**Comment by gurhub** [comment]
Hi and thank you :) Actually a great idea! Contributions are always welcome, please feel free to send a pull request for this. 

Also, I don't have any free time to maintain this project anymore. But, I can review and send commits if needed any time.

Best
